### PR TITLE
Refactored so that rpc client doesn't rely on zenodb package

### PR DESCRIPTION
**Pull request by oxtoacart**
This refactoring removes the dependency of the rpc client on the zenodb package in order to fix getlantern/lantern-internal#670

### CODE REVIEW

**Comment by oxtoacart** [comment]
cc: @joesis @myleshorton

**Comment by joesis** [comment]
The change is LGTM. I updated dependencies to compile the code. Travis failed because of a panic of `zenodb/rpc/server` package which only occurs when testing with `-race`.

**Comment by joesis** [comment]
I don't think it's a blocker for this PR. `flashlight` don't use the RPC server code anyway.

**Comment by oxtoacart** [comment]
@joesis I fixed that test. It was just complaining that the connection was closed, which is expected.

**Comment by myleshorton** [comment]
OK I'm going to bring this in. The basic refactoring is to avoid hitting `rpc.init()` from the client side code path correct?

**Comment by oxtoacart** [comment]
@myleshorton It's to avoid hitting `zenodb.init()`. Clients really shouldn't depend on the zenodb server-side implementation stuff, just the common interfaces which is what they do now.

**Pull request merged**
