### PR TITLE
Fix issues with RPC client caused by new PERCENTILE support

### PR DESCRIPTION
**Pull request by oxtoacart**

### CODE REVIEW

**Comment by hwh33** [comment]
Is the goal to fix the issues @joesis brought up [here](https://github.com/getlantern/borda/pull/20#issuecomment-532214205)?  `borda/client/rpcclient` is not building with the latest commit on this PR.  Guessing you plan to make changes there though?

```
➜ borda git:(master) GO111MODULE=on go get github.com/getlantern/zenodb@3c10a3e1e30a8bd6d62778e32c9e841782f785c3
go: finding github.com/getlantern/zenodb v0.0.0-20190916183230-7b3204c032e3
go: finding github.com/getlantern/bytemap v0.0.0-20190914004255-0acf4d58df56
go: finding github.com/getlantern/zenodb 3c10a3e1e30a8bd6d62778e32c9e841782f785c3
go: downloading github.com/getlantern/zenodb v0.0.0-20190917142917-3c10a3e1e30a
go: extracting github.com/getlantern/zenodb v0.0.0-20190917142917-3c10a3e1e30a
go: downloading github.com/getlantern/bytemap v0.0.0-20190914004255-0acf4d58df56
go: extracting github.com/getlantern/bytemap v0.0.0-20190914004255-0acf4d58df56
➜ borda git:(master) ✗ GO111MODULE=on go build ./...
# github.com/getlantern/borda/client/rpcclient
client/rpcclient/rpc_client.go:99:52: cannot use func literal (type func(func(string, float64))) as type func(func(string, interface {})) in argument to inserter.Insert
client/rpcclient/rpc_client.go:101:22: cannot use val.Get() (type interface {}) as type float64 in argument to cb: need type assertion
```

**Comment by hwh33** [comment]
Sorry, didn't line up the changes with the build errors, but I see now that it's just changes to function signatures.  Looks good other than CI still being unhappy.

**Comment by oxtoacart** [comment]
Thanks @hwh33. Still working through the CI failure.

**Comment by oxtoacart** [comment]
Not sure what's up with CI. Test is passing locally. merging for now.

**Pull request merged**
